Postgresql transport
BookBeat/knightbus pull request #111
Opened 2024-04-04 14:12 UTC by viktor-h

2024-04-15 07:29 UTC, niclaslindstedt commented on knightbus-postgresql/src/KnightBus.PostgreSql.Management/PostgresManagementClient.cs
> +                ReadCount = reader.GetInt32(reader.GetOrdinal("read_count")),
Du skulle kunna flytta ut GetOrdinal-funktionerna utanför while-loopen eftersom de inte kommer ändras under loopen.

2024-04-15 07:48 UTC, niclaslindstedt commented on knightbus/examples/KnightBus.Examples.PostgreSql/Program.cs
> +        //await client.SendAsync(new SamplePoisonPostgresMessage { MessageBody = $"error_{Guid.NewGuid()}" } );
Should this commented-out code be removed?

2024-04-15 07:48 UTC, niclaslindstedt approved these changes
Very nice :)

2024-04-15 08:29 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql.Management/PostgresManagementClient.cs
> +                ReadCount = reader.GetInt32(reader.GetOrdinal("read_count")),
nice catch

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresChannelReceiver.cs
> +    private readonly TimeSpan _pollingSleepInterval = TimeSpan.FromSeconds(5);
Should this be configurable? 5 seconds might be too long in some scenarios

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresChannelReceiver.cs
> +    public async Task StartAsync(CancellationToken cancellationToken)
Fix this warning. Return the task or Task.Completed

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/NpgsqlDataReaderExtensions.cs
> +    public static async Task<List<PostgresMessage<T>>> ReadDeadLetterRows<T>(
IAsyncEnumerable instead?

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresBus.cs
> +        var stringValues = values.ToString().TrimEnd(',');
Optimization: do not add ',' if last row instead of modifying the entire string every time

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresBus.cs
> +public interface IPostgresBus
Add CancellationToken support!

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresQueueClient.cs
> +    {
CancellationToken?

2024-04-15 08:43 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/QueueInitializer.cs
> +    public static async Task InitQueue(PostgresQueueName queueName, NpgsqlDataSource npgsqlDataSource)
How will you manage to update to a newer version? Should schema version be included somewhere?

2024-04-15 08:43 UTC, NiklasArbin requested changes
Impressive work!

2024-04-15 09:09 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresChannelReceiver.cs
> +    private readonly TimeSpan _pollingSleepInterval = TimeSpan.FromSeconds(5);
yeah I will have a go at it. 

I would also like to explore a longer interval combined with LISTEN/NOTIFY. But that would still require polling since notifications are ephemeral.

2024-04-15 09:28 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresQueueClient.cs
> +    {
hmm yes GetMessagesAsync should have support for cancellation. But not CompleteAsync, AbandonByErrorAsync and DeadLetterMessageAsync if we are in the midst of processing a message during shutdown. But no new ones should be fetched.

2024-04-15 09:55 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresBus.cs
> +        var stringValues = values.ToString().TrimEnd(',');
Yes let's get rid of that. Especially better for large batch inserts when the cmd text can get big.

2024-04-15 10:10 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/QueueInitializer.cs
> +    public static async Task InitQueue(PostgresQueueName queueName, NpgsqlDataSource npgsqlDataSource)
Need to think a bit about how this should be handled. I have deliberately left it out because I might have to invent some migration support that works for a lot of tables sharing the same schema.

2024-04-15 11:31 UTC, viktor-h commented
> Impressive work!

thanks!

2024-04-15 11:44 UTC, mbaneryd commented on knightbus-postgresql/src/KnightBus.PostgreSql/QueueInitializer.cs
> + CREATE SCHEMA IF NOT EXISTS {SchemaName};
Do we have an idea on how to handle schema updates in the future, if needed?

2024-04-15 21:34 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/QueueInitializer.cs
> + CREATE SCHEMA IF NOT EXISTS {SchemaName};
Even though it only uses a small set of tables we might end up in a situation where we want to add functionality. For example a priority column to order by?

I can think of two ways at the moment. Run migrations for each queue on first application start YOLO style or have some bundled CLI tool that does all the queue creations and migrations with a connection string.

2024-04-16 10:49 UTC, NiklasArbin commented on knightbus-postgresql/src/KnightBus.PostgreSql/NpgsqlDataReaderExtensions.cs
> +    public static async Task<List<PostgresMessage<T>>> ReadDeadLetterRows<T>(
This will copy arrays multiple times in memory of not either sized properly or handled as IEnumerable

2024-04-16 13:12 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresChannelReceiver.cs
> +                var timeoutToken = new CancellationTokenSource(Settings.MessageLockTimeout);
https://github.com/BookBeat/knightbus/pull/111/commits/472ad53cbaffe4feb76407d720cbd6bf53c781e9 not perfect but should align better with message fetch time.

2024-04-16 16:05 UTC, viktor-h commented on knightbus-postgresql/src/KnightBus.PostgreSql/PostgresChannelReceiver.cs
> +                var timeoutToken = new CancellationTokenSource(Settings.MessageLockTimeout);
hmm this won't work. The timeoutToken will get disposed if declared once above message loop.

2024-04-17 11:26 UTC, merged