Blob saga storage
BookBeat/knightbus pull request #40
Opened 2020-08-27 12:54 UTC by mbaneryd

Blob Saga storage

2020-08-27 13:28 UTC, NiklasArbin requested changes

2020-08-27 13:28 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +using Microsoft.WindowsAzure.Storage;
Use the new library Azure.Storage.Blobs

2020-08-27 13:28 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            if (!await _container.ExistsAsync())
Use optimistic programming. Get the container and catch 404

2020-08-27 13:28 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            var json = await blob.DownloadTextAsync();
All async operatons awaited should have .ConfigureAwait(false)

2020-08-27 13:28 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            var blob = _container.GetBlockBlobReference(Filename(partitionKey, id));
There might be a lot of blobs to go through. What if we would use partition key as container name?

2020-08-27 13:28 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            if (!await blob.ExistsAsync())
Optimistic here too

2020-08-27 13:28 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            if (await blob.ExistsAsync())
Optimistic

2020-08-27 14:47 UTC, mbaneryd commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            var blob = _container.GetBlockBlobReference(Filename(partitionKey, id));
This will be used per storage account, and it is easier to search within a container than searching for containers.
And I think that when we specify the filename it will be a direct reference and not a search behind the hood

2020-08-27 14:56 UTC, mbaneryd commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            var blob = _container.GetBlockBlobReference(Filename(partitionKey, id));
Perhaps we can use the partitionkey as a folder instead?

2020-08-28 05:59 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            var blob = _container.GetBlockBlobReference(Filename(partitionKey, id));
> Perhaps we can use the partitionkey as a folder instead?
> 
> ![image](https://user-images.githubusercontent.com/681338/91459589-17751700-e887-11ea-8ca4-45ca8e5fca63.png)

Yes, partition key as folder would be better

2020-08-28 06:06 UTC, NiklasArbin requested changes

2020-08-28 06:06 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj
> +    <PackageReference Include="Azure.Storage.Blobs" Version="12.5.1" />
So now that we use the new Azure.Storage.Blobs we should also switch over to Azure.Storage.Queues and remove the old WindowsAzure.Storage reference. This is a major bump since it's a breaking change and will affect sagas already in flight

2020-08-28 06:06 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            try
Start by creating the saga and catch 409 conflict

2020-08-28 06:06 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +        private static string Filename(string partitionKey, string id) => $"{partitionKey}-{id}.json";
Inserting a '/ ' here would create the folder structure

2020-08-28 06:47 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +                        new BlobUploadOptions
Maybe also set content type as application/json for extra polish

2020-08-28 08:07 UTC, mbaneryd commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj
> +    <PackageReference Include="Azure.Storage.Blobs" Version="12.5.1" />
Yes, but I think we should do that in another PR

2020-08-28 08:08 UTC, mbaneryd commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            try
hmm, did not see any 409 when I tested it, need to check that again then

2020-08-28 08:11 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            try
Nevermind there is no way to change the mode from always overwriting the files

2020-08-28 08:11 UTC, NiklasArbin commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj
> +    <PackageReference Include="Azure.Storage.Blobs" Version="12.5.1" />
Ok, agree

2020-08-28 08:42 UTC, mbaneryd commented on knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs
> +            var blob = _container.GetBlockBlobReference(Filename(partitionKey, id));
Fixed

2020-08-28 08:55 UTC, NiklasArbin approved these changes

2020-08-28 08:59 UTC, merged