Add delete deadletter functionality
BookBeat/knightbus pull request #44
Opened 2020-10-07 13:36 UTC by andrevirdarson

2020-10-07 13:43 UTC, NiklasArbin requested changes

2020-10-07 13:43 UTC, NiklasArbin commented on knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj
> -    <Version>3.4.0</Version>
Ändra ctor för RedisBus är väl breaking?

2020-10-07 13:43 UTC, NiklasArbin commented on knightbus-redis/src/KnightBus.Redis/RedisManagementClient.cs
>      }
Would be good to be able to delete a specific deadletter message if possible

2020-10-07 13:55 UTC, andrevirdarson commented on knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj
> -    <Version>3.4.0</Version>
RedisConfiguration ärver från IRedisBusConfiguration så den breakar inte men vi kanske vill ha major ändå?

2020-10-07 13:55 UTC, andrevirdarson commented on knightbus-redis/src/KnightBus.Redis/RedisManagementClient.cs
>      }
I'm not sure how we would pick up the specific deadletter we want to delete?

2020-10-07 14:06 UTC, NiklasArbin commented on knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj
> -    <Version>3.4.0</Version>
Finns andra förändringar som är breaking

2020-10-08 08:09 UTC, NiklasArbin requested changes

2020-10-08 08:09 UTC, NiklasArbin commented on knightbus-redis/src/KnightBus.Redis.Messages/RedisDeadletter.cs
> +    public class RedisDeadletter<T> where T : IRedisMessage
This class should be in KnightBus.Redis, only interfaces in the messages package

2020-10-08 08:25 UTC, NiklasArbin approved these changes

2020-10-08 08:27 UTC, mbaneryd commented on knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj
> -    <Version>3.4.0</Version>
Enligt semver är det en Breaking att ändra typen på argumenten

2020-10-08 10:17 UTC, merged