Partitioning ServiceBus queues/topics separately
BookBeat/knightbus pull request #56
Opened 2021-01-26 14:24 UTC by albincarnstam

- Removed `EnablePartitioning` from `ServiceBusCreationOptions` since it applied to all ServiceBus queues/topics in the assembly.
- Added `KnightBus.Azure.ServiceBus.Messages.IPartitionedMessage` to replace partitioning functionality, but for control of each ServiceBus queue/topic.
    - For indicating if it should use partitioning, add `IPartitionedMessage` to `IServiceBusCommand`/`IServiceBusEvent` implementation instead.

Example:

```
public class CalculateSomethingCommand : IServiceBusCommand, IPartitionedMessage
{
    // ...
}
```

2021-01-26 14:38 UTC, NiklasArbin requested changes

2021-01-26 14:38 UTC, NiklasArbin commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Messages/IPartitionedMessage.cs
> +    /// Indicates the queue/topic should be partitioned across multiple message brokers.
Create the queue/topic as partitioned

2021-01-26 15:03 UTC, albincarnstam commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Messages/IPartitionedMessage.cs
> +    /// Indicates the queue/topic should be partitioned across multiple message brokers.
Fixat i senaste commiten

2021-01-26 15:24 UTC, NiklasArbin requested changes

2021-01-26 15:24 UTC, NiklasArbin commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusCreationOptions.cs
>      public class ServiceBusCreationOptions
Shouldn't all of this class's functionality be moved in the same way since it operates per message

2021-01-26 15:45 UTC, albincarnstam commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusCreationOptions.cs
>      public class ServiceBusCreationOptions
In separate interfaces?

2021-01-26 15:51 UTC, andrevirdarson commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusCreationOptions.cs
>      public class ServiceBusCreationOptions
Or maybe we could have default properties on the IServiceBusCommand that can be overridden if needed? Alternatively implementing an abstract class that can be inherited from with these properties instead of an interface when there is a need to configure queues/topics?

```
public interface IServiceBusCommand
    {
        public bool EnablePartitioning { get => false; }
    }

    public class Impl : IServiceBusCommand
    {
        public bool EnablePartitioning = true;
    }
```

2021-01-27 06:07 UTC, sebbo176 commented on documentation/source/messages.rst
> +		public string Message { get; set; }
This indentation is different from the rest of the file.

2021-01-27 07:03 UTC, NiklasArbin commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusCreationOptions.cs
>      public class ServiceBusCreationOptions
Then those props would be serialized and sent over the bus, which is a bit wierd.

2021-01-27 07:05 UTC, NiklasArbin commented
Thinking about this a bit more. I'm not sure if this belongs on the message. Do the sender need to know if the message is partitioned?

Maybe this belongs on the message mapping? What are your thoughts?

2021-01-27 07:11 UTC, andrevirdarson commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusCreationOptions.cs
>      public class ServiceBusCreationOptions
Ah true..

2021-01-27 08:34 UTC, albincarnstam commented
> Thinking about this a bit more. I'm not sure if this belongs on the message. Do the sender need to know if the message is partitioned?
> 
> Maybe this belongs on the message mapping? What are your thoughts?

Add a GetPartitioningSetting that is similar to GetQueueName (in MessageMapper)?

2021-01-28 07:08 UTC, NiklasArbin requested changes

2021-01-28 07:08 UTC, NiklasArbin commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/DefaultServiceBusCreationOptions.cs
> +    public class DefaultServiceBusCreationOptions : IServiceBusCreationOptions
Since the property is named Default the class can be named ServiceBusCreationOptions no need to prefix with default.

2021-01-28 07:08 UTC, NiklasArbin commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/IServiceBusConfiguration.cs
> +        DefaultServiceBusCreationOptions CreationOptions { get; }
Rename propname to DefaultCreationOptions

2021-01-28 09:17 UTC, andrevirdarson approved these changes

2021-01-28 09:17 UTC, andrevirdarson commented on knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs
> +        private IServiceBusCreationOptions GetServiceBusCreationOptions()
Is this something we want to extract, since it's the exact same code in QueueChannelReceiver and TopicChannelReceiver?

2021-01-28 09:18 UTC, NiklasArbin approved these changes

2021-01-28 16:00 UTC, merged