Throw if etag differs when updating blob saga
BookBeat/knightbus pull request #99
Opened 2023-07-06 13:55 UTC by PhilipRominBookBeat

### What
Throw an exception when updating saga data if the data has been modified since reading it

2023-07-06 14:16 UTC, NiklasArbin commented on knightbus/src/KnightBus.Core/Sagas/Saga.cs
> +        public string Etag { get; set; }
ETag is just for http, rename to ConcurrencyStamp or something similar

2023-07-06 14:24 UTC, PhilipRominBookBeat commented on knightbus/src/KnightBus.Core/Sagas/Saga.cs
> +        public string Etag { get; set; }
✔️

2023-07-13 08:58 UTC, NiklasArbin requested changes
Looks good, but remember to bump major and for all other packages that depend on core

2023-08-08 06:26 UTC, NiklasArbin approved these changes

2023-08-09 09:45 UTC, andrevirdarson approved these changes

2023-08-29 07:39 UTC, merged